when:
  - event: push

label:
  plaform: darvin/arm64

matrix:
  OSX_VERSION:
    - sonoma
    - ventura
    - monterey

steps:
  - name: build
    image: /bin/bash
    commands:
      - cd osx
      - packer init .
      - packer build -var macos_version=${OSX_VERSION} .
      - tart push sonoma_base gitea.hnatekmar.xyz/osx:${OSX_VERSION}-latest
      - tart prune --space-budget 25
      

