when:
  - platform: darwin/arm64
    event: push

steps:
  - name: build
    commands:
      - packer init .
      - packer build -var macos_version=${OSX_VERSION} .
      - tart push sonoma_base gitea.hnatekmar.xyz/osx:${OSX_VERSION}-latest
      - tart prune --space-budget 25
      
